"""Released StreamVLN source/catalog bridge.

This module is deliberately a data-only seam.  It joins an already admitted
canonical trajectory manifest and a Z32 cache; it does not parse RGB archives,
run a model, construct goals, or retain imagined state.  The public source
item is a small immutable composition around the existing
``CanonicalTrajectory`` owner from :mod:`j2j.data.splits`.

The complete production manifest and cache are generated by their respective
owners.  Consequently the catalog writer consumes a cache-owned metadata
iterator when one is available and fails closed when that iterator has not
yet been exposed.  Runtime opening remains useful for an already published
catalog and performs the final row checks through the cache's public
``read_global_rows`` method.
"""

from __future__ import annotations

from collections.abc import Iterable, Iterator, Mapping, Sequence
from dataclasses import dataclass
import hashlib
import json
import os
from pathlib import Path
import re
from typing import Any, Literal

from .keys import frame_key
from .splits import CanonicalAlias, CanonicalTrajectory


_SHA256 = re.compile(r"^[0-9a-fA-F]{64}$")
_HEX32 = re.compile(r"^[0-9a-fA-F]{64}$")
_SPLITS = frozenset({"train", "dev", "final_mp3d", "final_gibson", "excluded"})
_PROJECTIONS = frozenset({"project-train", "project-dev", "excluded"})
_SOURCE_IDS = frozenset({"R2R", "RxR"})
_CATALOG_SCHEMAS = frozenset(
    {"J2J_RELEASED_SOURCE_CATALOG_V1", "J2J_SOURCE_CATALOG_V1"}
)
_MANIFEST_SCHEMAS = frozenset(
    {
        "J2J_CANONICAL_MANIFEST_V1",
        "J2J_CANONICAL_SOURCE_MANIFEST_V1",
        "J2J_RELEASED_SOURCE_MANIFEST_V1",
    }
)
_CENSUS_SCHEMAS = frozenset(
    {
        "J2J_BUILD_CENSUS_RECEIPT_V1",
        "J2J_BUILD_CENSUS_SCOPE_RECEIPT_V1",
    }
)


class SourceError(ValueError):
    """Raised when a released source/catalog authority is not valid."""


class SourceAuthorityError(SourceError):
    """Raised before cache payload reads when an authority is malformed."""


class SourceJoinError(SourceError):
    """Raised when canonical rows and cache metadata do not join exactly."""


@dataclass(frozen=True)
class ReleasedSourceItem:
    """One immutable canonical trajectory plus its Z32 row locators.

    The field order is part of the D1A ABI.  In particular, no language,
    goal, grid, model tensor, or imagined state belongs in this object.
    """

    canonical_trajectory: CanonicalTrajectory
    split_partition: Literal[
        "train", "dev", "final_mp3d", "final_gibson", "excluded"
    ]
    projection_partition: Literal["project-train", "project-dev", "excluded"]
    annotation_sha256: str
    outer_manifest_ordinal: int
    cache_global_rows: tuple[int, ...]

    def __post_init__(self) -> None:
        if not isinstance(self.canonical_trajectory, CanonicalTrajectory):
            raise SourceError("canonical_trajectory must be CanonicalTrajectory")
        if type(self.canonical_trajectory.aliases) is not tuple or any(
            not isinstance(alias, CanonicalAlias)
            for alias in self.canonical_trajectory.aliases
        ):
            raise SourceError("canonical aliases must remain the existing immutable tuple")
        if type(self.canonical_trajectory.actions) is not tuple or not self.canonical_trajectory.actions:
            raise SourceError("canonical actions must remain a non-empty tuple")
        if self.split_partition not in _SPLITS:
            raise SourceError("split_partition is invalid")
        if self.projection_partition not in _PROJECTIONS:
            raise SourceError("projection_partition is invalid")
        expected_projection = _projection_for_split(self.split_partition)
        if self.projection_partition != expected_projection:
            raise SourceError("split and projection partitions are inconsistent")
        _require_sha(self.annotation_sha256, "annotation_sha256")
        if type(self.outer_manifest_ordinal) is not int or self.outer_manifest_ordinal < 0:
            raise SourceError("outer_manifest_ordinal must be a non-negative integer")
        if type(self.cache_global_rows) is not tuple:
            raise SourceError("cache_global_rows must be an immutable tuple")
        if len(self.cache_global_rows) != len(self.canonical_trajectory.actions):
            raise SourceError("cache locator count must equal canonical frame count")
        seen: set[int] = set()
        for value in self.cache_global_rows:
            if type(value) is not int or value < 0:
                raise SourceError("cache locators must be non-negative integers")
            if value in seen:
                raise SourceError("cache locators must be unique per trajectory")
            seen.add(value)


def _projection_for_split(split: str) -> str:
    if split == "train":
        return "project-train"
    if split == "dev":
        return "project-dev"
    return "excluded"


def _require_sha(value: object, label: str) -> str:
    if type(value) is not str or _SHA256.fullmatch(value) is None:
        raise SourceAuthorityError(f"{label} must be exactly 64 hexadecimal characters")
    return value.lower()


def _require_hex32(value: object, label: str) -> bytes:
    if type(value) is not str or _HEX32.fullmatch(value) is None:
        raise SourceAuthorityError(f"{label} must be exactly 32 raw bytes in hex")
    return bytes.fromhex(value)


def _canonical_json_bytes(value: Mapping[str, Any]) -> bytes:
    try:
        encoded = json.dumps(
            value,
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=True,
            allow_nan=False,
        ).encode("utf-8")
    except (TypeError, ValueError) as exc:
        raise SourceAuthorityError("artifact contains non-canonical JSON values") from exc
    return encoded


def _sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def _read_bytes(path: Path, *, label: str) -> bytes:
    try:
        return path.read_bytes()
    except OSError as exc:
        raise SourceAuthorityError(f"{label} is missing or unreadable") from exc


def _resolve_path(root: Path, value: object, *, label: str) -> Path:
    if type(value) is not str or not value:
        raise SourceAuthorityError(f"{label} path must be a non-empty relative string")
    candidate = Path(value)
    if candidate.is_absolute() or ".." in candidate.parts:
        raise SourceAuthorityError(f"{label} path must stay below its manifest root")
    result = root / candidate
    try:
        result.relative_to(root)
    except ValueError as exc:  # pragma: no cover - defensive for odd Path flavours
        raise SourceAuthorityError(f"{label} path escapes its manifest root") from exc
    return result


def _pathlike(value: object, *, label: str) -> Path:
    if isinstance(value, (str, os.PathLike)):
        return Path(value)
    raise SourceAuthorityError(f"{label} must be a path-like locator")


def _load_json_file(path: Path, *, label: str, expected_sha256: str | None = None) -> tuple[Any, bytes]:
    raw = _read_bytes(path, label=label)
    if expected_sha256 is not None:
        expected = _require_sha(expected_sha256, f"expected {label} SHA-256")
        if _sha256_bytes(raw) != expected:
            raise SourceAuthorityError(f"{label} SHA-256 mismatch")
    try:
        value = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise SourceAuthorityError(f"{label} is not valid JSON") from exc
    return value, raw


def _descriptor_path(root: Path, descriptor: object, *, label: str) -> Path:
    if isinstance(descriptor, str):
        return _resolve_path(root, descriptor, label=label)
    if not isinstance(descriptor, Mapping):
        raise SourceAuthorityError(f"{label} descriptor is invalid")
    for key in ("relpath", "path", "relative_path", "file"):
        if key in descriptor:
            return _resolve_path(root, descriptor[key], label=label)
    raise SourceAuthorityError(f"{label} descriptor has no relative path")


def _load_jsonl_descriptor(
    root: Path, descriptor: object, *, label: str
) -> tuple[tuple[Mapping[str, Any], ...], bytes, Path]:
    """Read a canonical JSONL descriptor and verify declared bytes/count/SHA."""

    path = _descriptor_path(root, descriptor, label=label)
    raw = _read_bytes(path, label=label)
    if isinstance(descriptor, Mapping):
        if "bytes" in descriptor and type(descriptor["bytes"]) is not int:
            raise SourceAuthorityError(f"{label} byte count is invalid")
        if "bytes" in descriptor and descriptor["bytes"] != len(raw):
            raise SourceAuthorityError(f"{label} byte count mismatch")
        if "sha256" in descriptor:
            declared = _require_sha(descriptor["sha256"], f"{label} SHA-256")
            if declared != _sha256_bytes(raw):
                raise SourceAuthorityError(f"{label} SHA-256 mismatch")
    lines = raw.splitlines(keepends=True)
    rows: list[Mapping[str, Any]] = []
    for line in lines:
        if not line.endswith(b"\n"):
            raise SourceAuthorityError(f"{label} row is missing a final LF")
        try:
            value = json.loads(line[:-1].decode("utf-8"))
        except (UnicodeDecodeError, json.JSONDecodeError) as exc:
            raise SourceAuthorityError(f"{label} contains invalid JSONL") from exc
        if not isinstance(value, Mapping):
            raise SourceAuthorityError(f"{label} row must be a mapping")
        if _canonical_json_bytes(value) != line[:-1]:
            raise SourceAuthorityError(f"{label} row is not canonical JSON")
        rows.append(value)
    if isinstance(descriptor, Mapping) and "row_count" in descriptor:
        if type(descriptor["row_count"]) is not int or descriptor["row_count"] != len(rows):
            raise SourceAuthorityError(f"{label} row count mismatch")
    return tuple(rows), raw, path


def _first_present(mapping: Mapping[str, Any], names: Sequence[str]) -> object | None:
    for name in names:
        if name in mapping:
            return mapping[name]
    return None


def _alias_from_mapping(raw: object) -> CanonicalAlias:
    if not isinstance(raw, Mapping):
        raise SourceAuthorityError("canonical alias must be a mapping")
    try:
        source_id = raw["source_id"]
        row_index = raw["annotation_row_index"]
        prefix = raw["canonical_video_prefix"]
        key = raw["trajectory_key"]
        scan_id = raw["scan_id"]
    except KeyError as exc:
        raise SourceAuthorityError("canonical alias is missing a required field") from exc
    if source_id not in _SOURCE_IDS:
        raise SourceAuthorityError("canonical alias source_id is invalid")
    if type(row_index) is not int or row_index < 0:
        raise SourceAuthorityError("canonical alias annotation_row_index is invalid")
    if type(prefix) is not str or not prefix:
        raise SourceAuthorityError("canonical alias video prefix is invalid")
    if type(scan_id) is not str or not scan_id:
        raise SourceAuthorityError("canonical alias scan_id is invalid")
    return CanonicalAlias(
        source_id=source_id,
        annotation_row_index=row_index,
        canonical_video_prefix=prefix,
        trajectory_key=_require_hex32(key, "canonical alias trajectory_key"),
        scan_id=scan_id,
    )


def _actions(raw: object) -> tuple[int, ...]:
    if not isinstance(raw, (list, tuple)) or not raw:
        raise SourceAuthorityError("canonical actions must be a non-empty sequence")
    values = tuple(raw)
    if type(values[0]) is not int or values[0] != -1:
        raise SourceAuthorityError("canonical actions must start with BOS -1")
    if any(type(value) is not int or value < 0 or value > 3 for value in values[1:]):
        raise SourceAuthorityError("canonical actions contain an invalid action id")
    return values


def _sha_sequence(raw: object, *, label: str, length: int) -> tuple[str, ...]:
    if not isinstance(raw, (list, tuple)) or len(raw) != length:
        raise SourceAuthorityError(f"{label} must contain one SHA per frame")
    return tuple(_require_sha(value, f"{label} entry") for value in raw)


def _canonical_from_row(
    raw: Mapping[str, Any], *, aliases: Sequence[object] | None = None
) -> CanonicalTrajectory:
    nested = raw.get("canonical_trajectory")
    base: Mapping[str, Any] = nested if isinstance(nested, Mapping) else raw
    required = (
        "canonical_trajectory_key",
        "dedup_key",
        "scan_id",
        "source_id",
        "annotation_row_index",
        "canonical_video_prefix",
        "actions",
        "compressed_jpeg_sha256s",
        "decoded_rgb_sha256s",
    )
    missing = [name for name in required if name not in base]
    if missing:
        raise SourceAuthorityError(f"canonical trajectory is missing {missing[0]}")
    source_id = base["source_id"]
    if source_id not in _SOURCE_IDS:
        raise SourceAuthorityError("canonical trajectory source_id is invalid")
    scan_id = base["scan_id"]
    if type(scan_id) is not str or not scan_id:
        raise SourceAuthorityError("canonical trajectory scan_id is invalid")
    row_index = base["annotation_row_index"]
    if type(row_index) is not int or row_index < 0:
        raise SourceAuthorityError("canonical trajectory annotation_row_index is invalid")
    prefix = base["canonical_video_prefix"]
    if type(prefix) is not str or not prefix:
        raise SourceAuthorityError("canonical trajectory video prefix is invalid")
    action_values = _actions(base["actions"])
    compressed = _sha_sequence(
        base["compressed_jpeg_sha256s"],
        label="compressed_jpeg_sha256s",
        length=len(action_values),
    )
    decoded = _sha_sequence(
        base["decoded_rgb_sha256s"],
        label="decoded_rgb_sha256s",
        length=len(action_values),
    )
    raw_aliases = aliases
    if raw_aliases is None:
        candidate = base.get("aliases")
        raw_aliases = candidate if isinstance(candidate, (list, tuple)) else None
    if raw_aliases is None:
        raise SourceAuthorityError("canonical trajectory aliases are missing")
    parsed_aliases = tuple(_alias_from_mapping(alias) for alias in raw_aliases)
    if not parsed_aliases:
        raise SourceAuthorityError("canonical trajectory aliases cannot be empty")
    canonical_key = _require_hex32(
        base["canonical_trajectory_key"], "canonical_trajectory_key"
    )
    if parsed_aliases[0].trajectory_key != canonical_key:
        # The representative is required to be present, but aliases need not
        # be sorted by source.py; canonicalization remains owned by splits.py.
        if canonical_key not in {alias.trajectory_key for alias in parsed_aliases}:
            raise SourceAuthorityError("canonical representative is absent from aliases")
    if any(alias.scan_id != scan_id for alias in parsed_aliases):
        raise SourceAuthorityError("canonical aliases cross scan identities")
    return CanonicalTrajectory(
        canonical_trajectory_key=canonical_key,
        dedup_key=_require_hex32(base["dedup_key"], "dedup_key"),
        scan_id=scan_id,
        source_id=source_id,
        annotation_row_index=row_index,
        canonical_video_prefix=prefix,
        actions=action_values,
        compressed_jpeg_sha256s=compressed,
        decoded_rgb_sha256s=decoded,
        aliases=parsed_aliases,
    )


def _source_annotation_sha(row: Mapping[str, Any], outer: Mapping[str, Any]) -> str:
    direct = _first_present(row, ("annotation_sha256", "annotation_revision_sha256"))
    if direct is not None:
        return _require_sha(direct, "annotation_sha256")
    source_id = row.get("source_id")
    candidates: list[object] = []
    for key in ("annotation_sha256s", "annotation_revisions", "annotation_files"):
        value = outer.get(key)
        if isinstance(value, Mapping) and source_id in value:
            candidates.append(value[source_id])
    identity = outer.get("input_identity")
    if isinstance(identity, Mapping):
        assets = identity.get("assets")
        if isinstance(assets, Sequence) and not isinstance(assets, (str, bytes)):
            for asset in assets:
                if isinstance(asset, Mapping) and asset.get("dataset") == source_id:
                    if asset.get("role") == "annotation":
                        candidates.append(asset.get("sha256"))
    for candidate in candidates:
        if candidate is not None:
            return _require_sha(candidate, "annotation_sha256")
    raise SourceAuthorityError("representative row has no per-source annotation SHA")


def _split_and_projection(row: Mapping[str, Any]) -> tuple[str, str]:
    split_raw = _first_present(row, ("split_partition", "split", "raw_partition"))
    projection_raw = _first_present(row, ("projection_partition", "project_partition"))
    # Existing census output calls the five-way field simply ``partition``.
    if split_raw is None and row.get("partition") in _SPLITS:
        split_raw = row.get("partition")
    if split_raw is None and row.get("partition") in _PROJECTIONS:
        projection_raw = row.get("partition")
        split_raw = {"project-train": "train", "project-dev": "dev", "excluded": "excluded"}[projection_raw]
    if split_raw not in _SPLITS:
        raise SourceAuthorityError("canonical row split_partition is invalid")
    expected = _projection_for_split(split_raw)
    if projection_raw is None:
        projection_raw = expected
    if projection_raw != expected:
        raise SourceAuthorityError("canonical row split/projection mismatch")
    return split_raw, projection_raw


@dataclass(frozen=True)
class _ManifestRows:
    path: Path
    raw_bytes: bytes
    outer: Mapping[str, Any]
    trajectories: tuple[Mapping[str, Any], ...]
    aliases_by_key: Mapping[bytes, tuple[Mapping[str, Any], ...]]
    items: tuple[CanonicalManifestEntry, ...]


@dataclass(frozen=True)
class CanonicalManifestEntry:
    """Canonical manifest metadata before catalog locators are joined."""

    canonical_trajectory: CanonicalTrajectory
    split_partition: str
    projection_partition: str
    annotation_sha256: str
    outer_manifest_ordinal: int


def _load_alias_rows(root: Path, outer: Mapping[str, Any]) -> tuple[Mapping[str, Any], ...]:
    descriptor = _first_present(
        outer,
        ("alias", "aliases", "alias_ledger", "canonical_aliases", "full_aliases"),
    )
    if descriptor is None:
        return ()
    if isinstance(descriptor, list):
        if any(not isinstance(value, Mapping) for value in descriptor):
            raise SourceAuthorityError("alias ledger contains a non-mapping row")
        return tuple(descriptor)
    rows, _, _ = _load_jsonl_descriptor(root, descriptor, label="alias ledger")
    return rows


def _load_manifest(path: Path, *, expected_sha256: str) -> _ManifestRows:
    outer_value, raw_bytes = _load_json_file(
        path, label="canonical manifest", expected_sha256=expected_sha256
    )
    if not isinstance(outer_value, Mapping):
        raise SourceAuthorityError("canonical manifest must be a mapping")
    outer = outer_value
    schema = outer.get("schema")
    if schema in _CENSUS_SCHEMAS or schema == "J2J_BUILD_CENSUS_RECEIPT_V1":
        raise SourceAuthorityError("census receipt cannot masquerade as canonical source manifest")
    # Runtime authority is an explicit writer-produced descriptor.  A bare
    # JSON mapping (including a census receipt's nested reference) is not an
    # outer manifest; only the explicitly marked algebraic fixture below may
    # omit the production schema.
    if schema not in _MANIFEST_SCHEMAS and not (
        schema == "UNIT_TEST_ONLY" and outer.get("asset_scope") == "UNIT_TEST_ONLY"
    ):
        raise SourceAuthorityError("canonical manifest schema mismatch")
    if outer.get("production_eligible") is not None and type(outer.get("production_eligible")) is not bool:
        raise SourceAuthorityError("canonical manifest production eligibility is invalid")
    trajectory_descriptor = _first_present(
        outer,
        (
            "trajectory",
            "trajectories",
            "full_trajectory",
            "full_trajectories",
            "canonical_trajectories",
        ),
    )
    if trajectory_descriptor is None:
        # A list of embedded rows is useful only for explicit algebraic
        # fixtures.  It cannot be accepted for production authority.
        if outer.get("asset_scope") == "UNIT_TEST_ONLY" and isinstance(outer.get("rows"), list):
            trajectories = tuple(value for value in outer["rows"] if isinstance(value, Mapping))
        else:
            raise SourceAuthorityError("canonical manifest has no complete trajectory ledger")
    elif isinstance(trajectory_descriptor, list):
        trajectories = tuple(value for value in trajectory_descriptor if isinstance(value, Mapping))
    else:
        trajectories, _, _ = _load_jsonl_descriptor(
            path.parent, trajectory_descriptor, label="trajectory ledger"
        )
    if not trajectories:
        raise SourceAuthorityError("canonical trajectory ledger is empty")
    alias_rows = _load_alias_rows(path.parent, outer)
    aliases_by_key_mut: dict[bytes, tuple[Mapping[str, Any], ...]] = {}
    for alias_row in alias_rows:
        if not isinstance(alias_row, Mapping):
            raise SourceAuthorityError("alias ledger row is invalid")
        key = _require_hex32(
            alias_row.get("canonical_trajectory_key"),
            "alias canonical_trajectory_key",
        )
        raw_aliases = alias_row.get("aliases")
        if not isinstance(raw_aliases, list) or not raw_aliases:
            raise SourceAuthorityError("alias ledger row has no aliases")
        if key in aliases_by_key_mut:
            raise SourceAuthorityError("duplicate alias ledger canonical key")
        aliases_by_key_mut[key] = tuple(
            alias for alias in raw_aliases if isinstance(alias, Mapping)
        )
        if len(aliases_by_key_mut[key]) != len(raw_aliases):
            raise SourceAuthorityError("alias ledger contains a non-mapping alias")

    parsed_items: list[CanonicalManifestEntry] = []
    previous_key: bytes | None = None
    for ordinal, row in enumerate(trajectories):
        if not isinstance(row, Mapping):
            raise SourceAuthorityError("trajectory ledger row is invalid")
        nested = row.get("canonical_trajectory")
        base = nested if isinstance(nested, Mapping) else row
        key = _require_hex32(base.get("canonical_trajectory_key"), "canonical_trajectory_key")
        if previous_key is not None and key <= previous_key:
            raise SourceAuthorityError("canonical trajectory rows are not strictly raw-key sorted")
        previous_key = key
        aliases = aliases_by_key_mut.get(key)
        canonical = _canonical_from_row(row, aliases=aliases)
        split, projection = _split_and_projection(row)
        annotation_sha = _source_annotation_sha({**base, **row}, outer)
        parsed_items.append(
            CanonicalManifestEntry(
                canonical_trajectory=canonical,
                split_partition=split,
                projection_partition=projection,
                annotation_sha256=annotation_sha,
                outer_manifest_ordinal=ordinal,
            )
        )
    return _ManifestRows(
        path=path,
        raw_bytes=raw_bytes,
        outer=outer,
        trajectories=trajectories,
        aliases_by_key=aliases_by_key_mut,
        items=tuple(parsed_items),
    )


def load_canonical_manifest_partition(
    canonical_manifest: str | os.PathLike[str],
    *,
    expected_manifest_sha256: str,
    partition: Literal["project-train", "project-dev"],
    require_production_eligible: bool = True,
) -> tuple[CanonicalManifestEntry, ...]:
    """Read one canonical partition without opening or materializing its cache.

    This is the manifest-only authority seam used by source-derived ledgers such
    as STOP calibration.  It deliberately reuses the same strict parser as
    :func:`open_released_streamvln_source`; it does not create a second row
    schema or infer facts from a downstream ledger.
    """

    if partition not in {"project-train", "project-dev"}:
        raise SourceAuthorityError(
            "source partition must be project-train or project-dev"
        )
    if type(require_production_eligible) is not bool:
        raise SourceAuthorityError(
            "production eligibility requirement must be boolean"
        )
    expected_sha = _require_sha(
        expected_manifest_sha256, "expected manifest SHA-256"
    )
    manifest_path = _pathlike(canonical_manifest, label="canonical manifest")
    if not manifest_path.is_file():
        raise SourceAuthorityError("canonical manifest is missing")
    manifest = _load_manifest(manifest_path, expected_sha256=expected_sha)
    if (
        require_production_eligible
        and manifest.outer.get("production_eligible") is not True
    ):
        raise SourceAuthorityError("canonical manifest is not production eligible")
    return tuple(
        item for item in manifest.items if item.projection_partition == partition
    )


def _cache_manifest(cache_store: object) -> Mapping[str, Any] | None:
    value = getattr(cache_store, "manifest", None)
    if isinstance(value, Mapping):
        return value
    getter = getattr(cache_store, "cache_manifest", None)
    if callable(getter):
        candidate = getter()
        if isinstance(candidate, Mapping):
            return candidate
    return None


def _cache_manifest_sha256(
    cache_store: object, manifest: Mapping[str, Any] | None = None
) -> str | None:
    """Return an observable exact SHA for the admitted cache manifest."""

    direct = getattr(cache_store, "manifest_sha256", None)
    if isinstance(direct, str) and _SHA256.fullmatch(direct):
        return direct.lower()
    output = getattr(cache_store, "output", None)
    if output is not None:
        try:
            path = Path(output) / "manifest.json"
            if path.is_file():
                return _sha256_bytes(path.read_bytes())
        except (OSError, TypeError, ValueError):
            pass
    if manifest is not None:
        value = manifest.get("manifest_sha256")
        if isinstance(value, str) and _SHA256.fullmatch(value):
            return value.lower()
    return None


def _validate_cache_authority(
    cache_store: object,
    catalog: Mapping[str, Any],
    *,
    require_production_eligible: bool,
) -> None:
    reader = getattr(cache_store, "read_global_rows", None)
    if not callable(reader):
        raise SourceAuthorityError("cache_store must expose read_global_rows")
    manifest = _cache_manifest(cache_store)
    if manifest is None:
        # A test double may intentionally expose only the read API.  The
        # row-level check remains authoritative when items are read.
        if require_production_eligible and catalog.get("production_eligible") is not True:
            raise SourceAuthorityError("production source requires an admitted cache manifest")
        return
    if manifest.get("schema") != "J2J_LATENT_CACHE_V1":
        raise SourceAuthorityError("cache manifest schema mismatch")
    if manifest.get("stage") not in {"Z32", "RAW32"}:
        raise SourceAuthorityError("source bridge requires a Z32 or RAW32 cache")
    if manifest.get("training_eligible") is not True:
        raise SourceAuthorityError("cache is not training eligible")
    if require_production_eligible and manifest.get("production_eligible") is not True:
        raise SourceAuthorityError("cache is not production eligible")
    if "cache_stage" in catalog and catalog["cache_stage"] != manifest.get("stage"):
        raise SourceAuthorityError("catalog/cache stage mismatch")
    cache_sha = _cache_manifest_sha256(cache_store, manifest)
    if "cache_manifest_sha256" in catalog and cache_sha is not None:
        if _require_sha(catalog["cache_manifest_sha256"], "cache manifest") != cache_sha:
            raise SourceAuthorityError("catalog/cache manifest SHA mismatch")
    if "z32_manifest_sha256" in catalog and cache_sha is not None:
        left = _require_sha(catalog["z32_manifest_sha256"], "z32_manifest_sha256")
        if left != cache_sha:
            raise SourceAuthorityError("catalog/cache z32 manifest SHA mismatch")
    for catalog_key, cache_key in (
        ("cache_frame_ledger_sha256", "frame_ledger_sha256"),
        ("z32_frame_ledger_sha256", "frame_ledger_sha256"),
        ("frame_ledger_sha256", "frame_ledger_sha256"),
        ("split_ledger_sha256", "split_ledger_sha256"),
        ("alias_ledger_sha256", "trajectory_alias_ledger_sha256"),
    ):
        if catalog_key in catalog and cache_key in manifest:
            left = _require_sha(catalog[catalog_key], catalog_key)
            right = _require_sha(manifest[cache_key], cache_key)
            if left != right:
                raise SourceAuthorityError(f"catalog/cache {catalog_key} mismatch")


def _catalog_rows(value: Mapping[str, Any], root: Path) -> tuple[Mapping[str, Any], ...]:
    rows_value = value.get("rows")
    if isinstance(rows_value, list):
        rows = tuple(row for row in rows_value if isinstance(row, Mapping))
        if len(rows) != len(rows_value):
            raise SourceAuthorityError("source catalog rows contain a non-mapping")
        return rows
    descriptor = _first_present(value, ("row_ledger", "catalog", "entries"))
    if descriptor is None:
        raise SourceAuthorityError("source catalog has no row ledger")
    rows, _, _ = _load_jsonl_descriptor(root, descriptor, label="source catalog row ledger")
    return rows


def _load_catalog(path: Path, *, expected_manifest_sha256: str, cache_store: object, require_production_eligible: bool) -> tuple[Mapping[str, Any], tuple[Mapping[str, Any], ...], bytes]:
    value, raw = _load_json_file(path, label="source catalog")
    if not raw.endswith(b"\n"):
        raise SourceAuthorityError("source catalog must end with one LF")
    if not isinstance(value, Mapping) or value.get("schema") not in _CATALOG_SCHEMAS:
        raise SourceAuthorityError("source catalog schema mismatch")
    if _canonical_json_bytes(value) + b"\n" != raw:
        raise SourceAuthorityError("source catalog bytes are not canonical JSON")
    expected = _require_sha(expected_manifest_sha256, "expected manifest SHA-256")
    declared = _first_present(value, ("canonical_manifest_sha256", "manifest_sha256"))
    if declared is None or _require_sha(declared, "catalog canonical manifest SHA-256") != expected:
        raise SourceAuthorityError("source catalog is bound to a different canonical manifest")
    if value.get("production_eligible") is not None and type(value.get("production_eligible")) is not bool:
        raise SourceAuthorityError("source catalog production eligibility is invalid")
    if require_production_eligible and value.get("production_eligible") is not True:
        raise SourceAuthorityError("production source catalog is not eligible")
    _validate_cache_authority(
        cache_store, value, require_production_eligible=require_production_eligible
    )
    rows = _catalog_rows(value, path.parent)
    if not rows:
        raise SourceAuthorityError("source catalog row ledger is empty")
    return value, rows, raw


def _catalog_item(
    row: Mapping[str, Any],
    *,
    manifest_item: _ManifestEntry,
) -> ReleasedSourceItem:
    key = _require_hex32(
        _first_present(row, ("canonical_trajectory_key", "trajectory_key")),
        "catalog canonical_trajectory_key",
    )
    if key != manifest_item.canonical_trajectory.canonical_trajectory_key:
        raise SourceJoinError("catalog trajectory key does not match manifest")
    ordinal_raw = _first_present(row, ("outer_manifest_ordinal", "canonical_manifest_ordinal", "ordinal"))
    if type(ordinal_raw) is not int or ordinal_raw != manifest_item.outer_manifest_ordinal:
        raise SourceJoinError("catalog outer ordinal does not match manifest")
    split = row.get("split_partition", manifest_item.split_partition)
    projection = row.get("projection_partition", row.get("partition", manifest_item.projection_partition))
    if split != manifest_item.split_partition or projection != manifest_item.projection_partition:
        raise SourceJoinError("catalog partition does not match manifest")
    annotation = _first_present(row, ("annotation_sha256", "annotation_revision_sha256"))
    if annotation is None:
        annotation = manifest_item.annotation_sha256
    if _require_sha(annotation, "catalog annotation_sha256") != manifest_item.annotation_sha256:
        raise SourceJoinError("catalog annotation SHA does not match manifest")
    locators_raw = _first_present(row, ("cache_global_rows", "global_rows", "cache_rows"))
    if not isinstance(locators_raw, (list, tuple)):
        raise SourceJoinError("catalog cache_global_rows is missing")
    locators = tuple(locators_raw)
    try:
        return ReleasedSourceItem(
            canonical_trajectory=manifest_item.canonical_trajectory,
            split_partition=manifest_item.split_partition,
            projection_partition=manifest_item.projection_partition,
            annotation_sha256=manifest_item.annotation_sha256,
            outer_manifest_ordinal=manifest_item.outer_manifest_ordinal,
            cache_global_rows=locators,
        )
    except SourceError as exc:
        raise SourceJoinError("catalog cache locators are invalid") from exc


class ReleasedStreamVLNSource(Sequence[ReleasedSourceItem]):
    """Map-style metadata view over one admitted source partition."""

    def __init__(
        self,
        items: tuple[ReleasedSourceItem, ...],
        *,
        cache_store: object,
        catalog_raw: bytes,
        manifest_sha256: str,
    ) -> None:
        self._items = items
        self._cache_store = cache_store
        self._catalog_raw = catalog_raw
        self.manifest_sha256 = manifest_sha256

    def __len__(self) -> int:
        return len(self._items)

    def __iter__(self) -> Iterator[ReleasedSourceItem]:
        return iter(self._items)

    def __getitem__(self, index: int | slice) -> ReleasedSourceItem | tuple[ReleasedSourceItem, ...]:
        if isinstance(index, slice):
            return self._items[index]
        if type(index) is not int:
            raise TypeError("source index must be an integer")
        return self._items[index]

    def read_cache_records(self, index: int) -> list[Any]:
        """Read and verify one item's existing cache rows on demand."""

        item = self[index]
        if not isinstance(item, ReleasedSourceItem):  # pragma: no cover
            raise TypeError("source index did not resolve to an item")
        reader = getattr(self._cache_store, "read_global_rows", None)
        if not callable(reader):
            raise SourceJoinError("cache_store must expose read_global_rows")
        try:
            records = list(reader(item.cache_global_rows))
        except Exception as exc:
            if isinstance(exc, SourceError):
                raise
            raise SourceJoinError("cache row read failed") from exc
        if len(records) != len(item.cache_global_rows):
            raise SourceJoinError("cache returned the wrong number of rows")
        expected_key = item.canonical_trajectory.canonical_trajectory_key
        for step, record in enumerate(records):
            actual_frame_key = getattr(record, "frame_key", None)
            if actual_frame_key != frame_key(expected_key, step):
                raise SourceJoinError("cache frame key does not match trajectory/time")
            for attr, expected_values, label in (
                (
                    "compressed_jpeg_sha256",
                    item.canonical_trajectory.compressed_jpeg_sha256s,
                    "compressed JPEG",
                ),
                (
                    "decoded_rgb_sha256",
                    item.canonical_trajectory.decoded_rgb_sha256s,
                    "decoded RGB",
                ),
            ):
                actual = getattr(record, attr, None)
                if type(actual) is not str or actual.lower() != expected_values[step]:
                    raise SourceJoinError(f"cache {label} identity does not match manifest")
            if getattr(record, "partition", None) != item.projection_partition:
                raise SourceJoinError("cache partition does not match source projection")
            if getattr(record, "source_dataset", None) != item.canonical_trajectory.source_id:
                raise SourceJoinError("cache source dataset does not match manifest")
        return records


def write_source_catalog(
    output_dir: str | os.PathLike[str],
    *,
    canonical_manifest: str | os.PathLike[str],
    expected_manifest_sha256: str,
    u_cache_manifest: str | os.PathLike[str] | Mapping[str, Any],
    z32_cache_store: object,
) -> Path:
    """Build a compact catalog from cache-owned validated index metadata.

    The current cache revision intentionally does not yet expose a public
    metadata iterator.  In that state this function validates all authorities
    and fails closed instead of parsing cache internals or asking callers to
    hand-write locators.  A future cache owner may expose
    ``iter_index_metadata`` (or the equivalent public protocol), at which point
    the same function can perform the streaming join without changing its
    ABI.
    """

    output = _pathlike(output_dir, label="catalog output")
    if output.exists() and not output.is_dir():
        raise SourceAuthorityError("catalog output path is not a directory")
    output.mkdir(parents=True, exist_ok=True)
    manifest_path = _pathlike(canonical_manifest, label="canonical manifest")
    manifest = _load_manifest(
        manifest_path, expected_sha256=_require_sha(expected_manifest_sha256, "expected manifest SHA-256")
    )
    manifest_production = manifest.outer.get("production_eligible")
    if type(manifest_production) is not bool:
        raise SourceAuthorityError("canonical manifest production eligibility is required")
    if isinstance(u_cache_manifest, Mapping):
        u_manifest = u_cache_manifest
    else:
        u_path = _pathlike(u_cache_manifest, label="U cache manifest")
        u_manifest, _ = _load_json_file(u_path, label="U cache manifest")
    if not isinstance(u_manifest, Mapping):
        raise SourceAuthorityError("U cache manifest must be a mapping")
    if u_manifest.get("schema") not in (None, "J2J_LATENT_CACHE_V1"):
        raise SourceAuthorityError("U cache manifest schema is invalid")
    cache_manifest = _cache_manifest(z32_cache_store)
    raw = cache_manifest is not None and cache_manifest.get("stage") == "RAW32"
    if raw:
        # RAW32 has no intermediate U generation: the compatibility argument
        # must identify the very same raw manifest already opened by the cache.
        if dict(u_manifest) != dict(cache_manifest):
            raise SourceAuthorityError("raw catalog manifest must match its opened cache")
    elif u_manifest.get("stage") not in (None, "U"):
        raise SourceAuthorityError("U cache manifest stage is invalid")
    manifest_key = "cache_manifest_sha256" if raw else "z32_manifest_sha256"
    frame_key_name = "cache_frame_ledger_sha256" if raw else "z32_frame_ledger_sha256"
    catalog_authority: dict[str, Any] = {
        "production_eligible": manifest_production,
    }
    if cache_manifest is not None:
        cache_sha = _cache_manifest_sha256(z32_cache_store, cache_manifest)
        if cache_sha is not None:
            catalog_authority[manifest_key] = cache_sha
        if "frame_ledger_sha256" in cache_manifest:
            catalog_authority[frame_key_name] = cache_manifest[
                "frame_ledger_sha256"
            ]
        if "trajectory_alias_ledger_sha256" in cache_manifest:
            catalog_authority["alias_ledger_sha256"] = cache_manifest[
                "trajectory_alias_ledger_sha256"
            ]
    _validate_cache_authority(
        z32_cache_store,
        catalog_authority,
        require_production_eligible=manifest_production,
    )
    metadata_iterator = None
    for name in ("iter_index_metadata", "iter_validated_index_metadata", "iter_metadata"):
        candidate = getattr(z32_cache_store, name, None)
        if callable(candidate):
            metadata_iterator = candidate
            break
    if metadata_iterator is None:
        raise SourceAuthorityError(
            "cache store has no public validated index-metadata iterator; catalog construction is blocked"
        )

    # Normalize the cache owner's stream into one bounded map.  This map is
    # only construction-time metadata; the published catalog itself stores
    # per-trajectory ordered locators and no grids.
    metadata: dict[bytes, tuple[int, Mapping[str, Any]]] = {}
    try:
        stream = metadata_iterator()
        for ordinal, entry in enumerate(stream):
            if isinstance(entry, tuple) and len(entry) == 2:
                global_row, row = entry
            elif isinstance(entry, Mapping):
                global_row = entry.get("global_row", entry.get("global_index"))
                row = entry
            else:
                raise SourceJoinError("cache metadata iterator yielded an invalid entry")
            if type(global_row) is not int or global_row < 0 or not isinstance(row, Mapping):
                raise SourceJoinError("cache metadata iterator yielded invalid row metadata")
            key = row.get("frame_key")
            if isinstance(key, str):
                if not re.fullmatch(r"[0-9a-fA-F]{72}", key):
                    raise SourceJoinError("cache frame_key metadata is invalid")
                raw_key = bytes.fromhex(key)
            else:
                raw_key = key
            if not isinstance(raw_key, bytes) or len(raw_key) != 36:
                raise SourceJoinError("cache frame_key metadata has the wrong length")
            if raw_key in metadata:
                raise SourceJoinError("cache frame keys are duplicated")
            metadata[raw_key] = (global_row, row)
    except SourceError:
        raise
    except Exception as exc:
        raise SourceJoinError("cache metadata iterator failed") from exc

    catalog_rows: list[dict[str, Any]] = []
    consumed: set[bytes] = set()
    for item in manifest.items:
        if item.projection_partition == "excluded":
            continue
        locators: list[int] = []
        for step in range(len(item.canonical_trajectory.actions)):
            expected_key = frame_key(item.canonical_trajectory.canonical_trajectory_key, step)
            if expected_key not in metadata:
                raise SourceJoinError("cache metadata is missing a canonical frame")
            global_row, cache_row = metadata[expected_key]
            if cache_row.get("partition") != item.projection_partition:
                raise SourceJoinError("cache frame partition does not match manifest")
            if cache_row.get("source_dataset") != item.canonical_trajectory.source_id:
                raise SourceJoinError("cache frame source does not match manifest")
            if cache_row.get("compressed_jpeg_sha256", "").lower() != item.canonical_trajectory.compressed_jpeg_sha256s[step]:
                raise SourceJoinError("cache compressed frame identity does not match manifest")
            if cache_row.get("decoded_rgb_sha256", "").lower() != item.canonical_trajectory.decoded_rgb_sha256s[step]:
                raise SourceJoinError("cache decoded frame identity does not match manifest")
            locators.append(global_row)
            consumed.add(expected_key)
        catalog_rows.append(
            {
                "canonical_trajectory_key": item.canonical_trajectory.canonical_trajectory_key.hex(),
                "split_partition": item.split_partition,
                "projection_partition": item.projection_partition,
                "annotation_sha256": item.annotation_sha256,
                "outer_manifest_ordinal": item.outer_manifest_ordinal,
                "cache_global_rows": locators,
            }
        )
    if set(metadata) != consumed:
        raise SourceJoinError("cache metadata contains extra frames outside the canonical manifest")
    catalog = {
        "schema": "J2J_RELEASED_SOURCE_CATALOG_V1",
        "canonical_manifest_sha256": _require_sha(expected_manifest_sha256, "manifest SHA-256"),
        "rows": catalog_rows,
        "production_eligible": manifest_production,
    }
    if raw:
        catalog["cache_stage"] = "RAW32"
    if cache_manifest is not None:
        cache_sha = _cache_manifest_sha256(z32_cache_store, cache_manifest)
        if cache_sha is not None:
            catalog[manifest_key] = cache_sha
        if "frame_ledger_sha256" in cache_manifest:
            catalog[frame_key_name] = cache_manifest[
                "frame_ledger_sha256"
            ]
        if "trajectory_alias_ledger_sha256" in cache_manifest:
            catalog["alias_ledger_sha256"] = cache_manifest[
                "trajectory_alias_ledger_sha256"
            ]
    destination = output / "J2J_RELEASED_SOURCE_CATALOG_V1.json"
    encoded = (json.dumps(catalog, sort_keys=True, separators=(",", ":"), ensure_ascii=True) + "\n").encode("utf-8")
    temporary = output / f".{destination.name}.tmp"
    try:
        with temporary.open("xb") as handle:
            handle.write(encoded)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, destination)
    except Exception:
        try:
            temporary.unlink()
        except OSError:
            pass
        raise
    return destination


def open_released_streamvln_source(
    *,
    canonical_manifest: str | os.PathLike[str],
    source_catalog: str | os.PathLike[str],
    cache_store: object,
    expected_manifest_sha256: str,
    partition: Literal["project-train", "project-dev"],
    require_production_eligible: bool = True,
) -> ReleasedStreamVLNSource:
    """Open one project partition after exact manifest/catalog authority checks."""

    if partition not in {"project-train", "project-dev"}:
        raise SourceAuthorityError("source partition must be project-train or project-dev")
    if type(require_production_eligible) is not bool:
        raise SourceAuthorityError("production eligibility requirement must be boolean")
    expected_sha = _require_sha(expected_manifest_sha256, "expected manifest SHA-256")
    # Validate both paths before touching cache_store.  This ordering is a
    # deliberate fail-closed contract used by the focused RED/GREEN test.
    manifest_path = _pathlike(canonical_manifest, label="canonical manifest")
    catalog_path = _pathlike(source_catalog, label="source catalog")
    if not manifest_path.is_file():
        raise SourceAuthorityError("canonical manifest is missing")
    if not catalog_path.is_file():
        raise SourceAuthorityError("source catalog is missing")
    manifest = _load_manifest(manifest_path, expected_sha256=expected_sha)
    if require_production_eligible and manifest.outer.get("production_eligible") is not True:
        raise SourceAuthorityError("canonical manifest is not production eligible")
    catalog, catalog_rows, catalog_raw = _load_catalog(
        catalog_path,
        expected_manifest_sha256=expected_sha,
        cache_store=cache_store,
        require_production_eligible=require_production_eligible,
    )
    by_ordinal: dict[int, ReleasedSourceItem] = {}
    for row in catalog_rows:
        ordinal_raw = _first_present(row, ("outer_manifest_ordinal", "canonical_manifest_ordinal", "ordinal"))
        if type(ordinal_raw) is not int or ordinal_raw in by_ordinal:
            raise SourceJoinError("source catalog ordinals are missing or duplicated")
        if ordinal_raw < 0 or ordinal_raw >= len(manifest.items):
            raise SourceJoinError("source catalog ordinal is out of range")
        item = _catalog_item(row, manifest_item=manifest.items[ordinal_raw])
        by_ordinal[ordinal_raw] = item
    result: list[ReleasedSourceItem] = []
    for item in manifest.items:
        if item.projection_partition != partition:
            continue
        catalog_item = by_ordinal.get(item.outer_manifest_ordinal)
        if catalog_item is None:
            raise SourceJoinError("eligible manifest row is absent from source catalog")
        result.append(catalog_item)
    # Catalog rows for another partition are harmless in the same artifact,
    # but excluded rows and duplicate/unknown rows are not.
    for ordinal, item in by_ordinal.items():
        if item.projection_partition == "excluded":
            raise SourceJoinError("excluded trajectory appears in source catalog")
        if item.projection_partition not in {"project-train", "project-dev"}:
            raise SourceJoinError("catalog projection partition is invalid")
        if ordinal != item.outer_manifest_ordinal:
            raise SourceJoinError("catalog ordinal binding is inconsistent")
    return ReleasedStreamVLNSource(
        tuple(result),
        cache_store=cache_store,
        catalog_raw=catalog_raw,
        manifest_sha256=expected_sha,
    )


__all__ = [
    "CanonicalManifestEntry",
    "ReleasedSourceItem",
    "ReleasedStreamVLNSource",
    "SourceAuthorityError",
    "SourceError",
    "SourceJoinError",
    "load_canonical_manifest_partition",
    "open_released_streamvln_source",
    "write_source_catalog",
]
