#!/usr/bin/env python3
"""Validate a RAE-stream manifest and official RAE loader ABI without writes."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import pickle
import stat
import sys
import tempfile
from typing import Any, Mapping, Sequence


def _bootstrap_repo() -> Path:
    root = Path(__file__).resolve().parents[1]
    if str(root) not in sys.path:
        sys.path.insert(0, str(root))
    return root


REPO_ROOT = _bootstrap_repo()
from rae_stream.config_guard import (  # noqa: E402
    OFFICIAL_COMMIT,
    STREAMVLN_ANNOTATION_ROW_COUNTS,
    STREAMVLN_ANNOTATION_SHA256,
    STREAMVLN_ARCHIVE_SHA256,
    STREAMVLN_REVISION,
    converter_bundle_sha256 as compute_converter_bundle_sha256,
    converter_closure_digest_map,
    verify_converter_source,
    verify_upstream_source,
)
from rae_stream.annotations import (  # noqa: E402
    find_frame_dir,
    load_annotation_file,
    numeric_frame_paths,
    scene_token_from_video,
)
from rae_stream.geometry import integrate_actions  # noqa: E402
from rae_stream.materialize import split_for_scene  # noqa: E402
from rae_stream.authority import verify_code_authority  # noqa: E402
from rae_stream.manifest import frame_sequence_sha256, read_jsonl  # noqa: E402


# This is a data-converter identity, not a model/training setting.  Keep the
# version check explicit so an old manifest cannot silently pass a formal gate
# after the converter's semantics have changed.
EXPECTED_CONVERTER_VERSION = "rae_stream_converter_v2"
FORMAL_MIN_LENGTH = 68
FORMAL_CONTEXT_SIZE = 4
FORMAL_LEN_TRAJ_PRED = 64
FORMAL_IMAGE_DECODE_SAMPLES = 8


def sha256_file(path: str | Path) -> str:
    digest = hashlib.sha256()
    with Path(path).open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _assert_readonly_path(path: str | Path, *, label: str) -> None:
    """Reject a required generated file/directory that remains writable."""

    target = Path(path)
    try:
        info = target.lstat()
    except OSError as exc:
        raise ValueError(f"{label} is not readable: {target}") from exc
    if stat.S_ISLNK(info.st_mode) or not (stat.S_ISREG(info.st_mode) or stat.S_ISDIR(info.st_mode)):
        raise ValueError(f"{label} must be a regular non-symlink path: {target}")
    if stat.S_IMODE(info.st_mode) & 0o222:
        raise ValueError(f"{label} is writable; expected readonly generated data: {target}")


def _assert_formal_layout_readonly(
    data_root: Path, split_root: Path, manifest_path: Path
) -> None:
    """Check immutable generated bytes without blocking the official split cache.

    ``datasets.py`` writes ``dataset_dist_*.pkl`` into each split directory at
    startup.  Consequently the split containers are intentionally writable;
    only their ``traj_names.txt`` files are frozen and checked later against
    the prepare receipt.  The generated trajectory tree, its container, and
    the manifest remain readonly here.
    """

    _assert_readonly_path(data_root, label="formal data root")
    _assert_readonly_path(manifest_path, label="formal manifest")
    _assert_readonly_path(data_root.parent, label="formal data parent")


def _verify_formal_prepare_receipt_identity(
    receipt: Mapping[str, Any],
    *,
    expected_converter_sha: str,
    expected_converter_source_sha256: Mapping[str, str],
    expected_converter_bundle_sha256: str,
) -> None:
    """Check the receipt's converter and immutable-source claims."""

    if receipt.get("converter_sha256") != expected_converter_sha:
        raise ValueError("prepare receipt converter SHA does not match reviewed bytes")
    if receipt.get("converter_source_sha256") != dict(expected_converter_source_sha256):
        raise ValueError("prepare receipt converter closure does not match reviewed bytes")
    if receipt.get("converter_bundle_sha256") != expected_converter_bundle_sha256:
        raise ValueError("prepare receipt converter bundle does not match reviewed bytes")
    immutable_sources = receipt.get("immutable_source_trees")
    if not isinstance(immutable_sources, Mapping) or immutable_sources != {"R2R": True, "RxR": True}:
        raise ValueError("formal validation requires immutable R2R/RxR source trees")


def _verify_formal_source_parent_identity(
    receipt: Mapping[str, Any], source_roots: Sequence[Path]
) -> None:
    """Require readonly containers so an entire selected-source tree cannot be replaced."""

    expected = {str(Path(root).resolve().parent): True for root in source_roots}
    declared = receipt.get("immutable_source_parent_dirs")
    if not isinstance(declared, Mapping) or dict(declared) != expected:
        raise ValueError("formal validation requires immutable selected-source parent directories")
    for parent in sorted(expected, key=str):
        _assert_readonly_path(parent, label="formal selected-source parent")


def _verify_immutable_path_identities(
    receipt: Mapping[str, Any], official_root: str | Path
) -> dict[str, dict[str, int]]:
    """Recheck lstat identities recorded after formal preparation.

    This is a cheap race guard: it detects rename/unlink replacement of the
    readonly data/source containers without repeating the full RGB digest pass.
    The receipt itself is externally SHA-pinned by the caller.
    """

    root = Path(official_root).resolve()
    raw_map = receipt.get("immutable_path_identities")
    if not isinstance(raw_map, Mapping) or not raw_map:
        raise ValueError("formal prepare receipt lacks immutable path identities")
    normalized: dict[str, dict[str, int]] = {}
    for raw_path, raw_identity in raw_map.items():
        path = _canonical_owned_path(str(raw_path), root, label="immutable path identity")
        if not isinstance(raw_identity, Mapping):
            raise ValueError(f"immutable path identity is malformed: {path}")
        try:
            expected = {
                "st_dev": int(raw_identity["st_dev"]),
                "st_ino": int(raw_identity["st_ino"]),
                "mode": int(raw_identity["mode"]),
            }
        except (KeyError, TypeError, ValueError) as exc:
            raise ValueError(f"immutable path identity is malformed: {path}") from exc
        try:
            info = path.lstat()
        except OSError as exc:
            raise ValueError(f"immutable path identity target is missing: {path}") from exc
        if stat.S_ISLNK(info.st_mode) or not (
            stat.S_ISREG(info.st_mode) or stat.S_ISDIR(info.st_mode)
        ):
            raise ValueError(f"immutable path identity target is not canonical: {path}")
        actual = {
            "st_dev": int(info.st_dev),
            "st_ino": int(info.st_ino),
            "mode": int(stat.S_IMODE(info.st_mode)),
        }
        if actual != expected:
            raise ValueError(f"immutable path identity changed: {path}")
        normalized[str(path)] = actual
    return normalized


def _verify_source_frame_digest(
    output_frames: Sequence[Path],
    source_frames: Sequence[Path],
    *,
    declared_output_digest: str,
    declared_source_digest: str,
) -> None:
    """Recompute source bytes and bind them to the output frame sequence.

    Formal materialization uses hardlinks or source-root-bound symlinks.  When
    every pair is the same inode, one source read proves both digests; copied
    files (used only by non-production probes) are independently hashed.
    """

    if len(output_frames) != len(source_frames):
        raise ValueError("source frame digest length mismatch")
    same_inode = True
    for output, source in zip(output_frames, source_frames):
        try:
            if not os.path.samefile(output, source):
                same_inode = False
                break
        except OSError:
            same_inode = False
            break
    actual_source = frame_sequence_sha256(source_frames)
    if actual_source != declared_source_digest:
        raise ValueError("source frame digest does not match source bytes")
    actual_output = actual_source if same_inode else frame_sequence_sha256(output_frames)
    if actual_output != declared_output_digest:
        raise ValueError("output frame digest does not match output bytes")


def _atomic_json(path: Path, value: Mapping[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=str(path.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            json.dump(value, handle, ensure_ascii=False, sort_keys=True, indent=2)
            handle.write("\n")
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    except Exception:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass
        raise


def _numeric_frames(directory: Path) -> list[Path]:
    frames: list[tuple[int, Path]] = []
    for path in directory.iterdir():
        if not path.is_file() or path.suffix.lower() != ".jpg":
            continue
        try:
            index = int(path.stem)
        except ValueError:
            raise ValueError(f"non-numeric frame filename: {path}")
        frames.append((index, path))
    frames.sort(key=lambda item: item[0])
    expected = list(range(len(frames)))
    actual = [item[0] for item in frames]
    if actual != expected:
        raise ValueError(f"frame indices must be contiguous 0..T-1 in {directory}, got {actual[:8]}...")
    return [item[1] for item in frames]


class _RestrictedUnpickler(pickle.Unpickler):
    """Load only the NumPy structures emitted by the converter.

    ``pickle.load`` executes arbitrary globals.  The manifest is an input
    boundary, so formal validation must not run attacker-controlled reducers
    before any source/identity gate has passed.
    """

    _ALLOWED_GLOBALS = {
        ("builtins", "dict"),
        ("builtins", "list"),
        ("builtins", "tuple"),
        ("builtins", "set"),
        ("builtins", "float"),
        ("builtins", "int"),
        ("builtins", "bytes"),
        ("builtins", "bytearray"),
        ("numpy", "ndarray"),
        ("numpy", "dtype"),
        ("numpy.core.multiarray", "_reconstruct"),
        ("numpy.core.multiarray", "scalar"),
        # NumPy 2.x serializes the same constructors under ``numpy._core``;
        # accepting these exact names keeps the loader ABI version-neutral
        # without opening arbitrary module imports.
        ("numpy._core.multiarray", "_reconstruct"),
        ("numpy._core.multiarray", "scalar"),
        ("numpy._core.numeric", "_frombuffer"),
        ("numpy._core", "multiarray"),
        ("_codecs", "encode"),
    }

    def find_class(self, module: str, name: str) -> Any:  # pragma: no cover - exercised by pickle fixtures
        if (module, name) not in self._ALLOWED_GLOBALS:
            raise pickle.UnpicklingError(f"disallowed pickle global {module}.{name}")
        return super().find_class(module, name)


def _safe_pickle_load(path: Path) -> Any:
    with path.open("rb") as handle:
        return _RestrictedUnpickler(handle).load()


def _action_digest(actions: Sequence[int]) -> str:
    return hashlib.sha256(
        json.dumps([int(action) for action in actions], separators=(",", ":")).encode("utf-8")
    ).hexdigest()


def _validate_pickle(
    path: Path,
    frame_count: int,
    command_actions: Sequence[int],
    expected_sha256: str | None = None,
) -> None:
    # ``Path.is_file`` follows symlinks.  The official loader opens this exact
    # pathname, so a symlink would let a manifest validate bytes outside the
    # canonical trajectory directory while training consumes them.
    if path.is_symlink() or not path.is_file():
        raise ValueError(f"{path} must be a regular non-symlink pickle")
    if path.parent.resolve() != path.parent:
        raise ValueError(f"{path} pickle parent is not canonical")
    if expected_sha256 is not None:
        actual_sha256 = sha256_file(path)
        if actual_sha256 != expected_sha256:
            raise ValueError(f"{path} pickle SHA mismatch")
    try:
        payload = _safe_pickle_load(path)
    except Exception as exc:
        raise ValueError(f"{path} restricted pickle load failed: {exc}") from exc
    if not isinstance(payload, dict) or set(payload) != {"position", "yaw"}:
        raise ValueError(f"{path} must contain only position and yaw numeric arrays")
    position = payload["position"]
    yaw = payload["yaw"]
    if getattr(position, "shape", None) != (frame_count, 2):
        raise ValueError(f"{path} position shape mismatch: {getattr(position, 'shape', None)}")
    if getattr(yaw, "shape", None) != (frame_count,):
        raise ValueError(f"{path} yaw shape mismatch: {getattr(yaw, 'shape', None)}")
    if str(getattr(position, "dtype", "")) != "float32" or str(getattr(yaw, "dtype", "")) != "float32":
        raise ValueError(f"{path} must use float32 position/yaw")
    try:
        import numpy as np

        if not np.isfinite(position).all() or not np.isfinite(yaw).all():
            raise ValueError(f"{path} contains non-finite pose values")
        expected = integrate_actions(command_actions)
        if len(command_actions) != frame_count:
            raise ValueError(f"{path} command/action length does not match frame count")
        if not np.array_equal(position, expected[:, :2].astype(np.float32)) or not np.array_equal(
            yaw, expected[:, 2].astype(np.float32)
        ):
            raise ValueError(f"{path} command-derived pose does not match command_actions")
    except ModuleNotFoundError as exc:  # pragma: no cover - converter dependency
        raise RuntimeError("NumPy is required for RAE pickle validation") from exc


def _decode_jpeg_sample(path: Path) -> None:
    """Decode and fully load one RGB sample without retaining pixel data."""

    try:
        from PIL import Image
    except ModuleNotFoundError as exc:  # pragma: no cover - runtime dependency
        raise RuntimeError("Pillow is required for formal image validation") from exc
    try:
        # ``verify`` checks the file structure; a second open/load exercises
        # the actual decoder and catches truncated scan data as well.
        with Image.open(path) as image:
            if image.format not in {"JPEG", "JPG"}:
                raise ValueError(f"expected JPEG payload, got {image.format!r}")
            image.verify()
        with Image.open(path) as image:
            image.convert("RGB").load()
    except Exception as exc:
        raise ValueError(f"JPEG decode failed for {path}: {exc}") from exc


def _canonical_owned_path(raw: str | Path, root: Path, *, label: str) -> Path:
    """Reject symlink/traversal paths before formal validation follows them."""

    candidate = Path(raw).expanduser()
    if not candidate.is_absolute():
        candidate = root / candidate
    candidate = candidate.absolute()
    try:
        relative = candidate.relative_to(root)
    except ValueError as exc:
        raise ValueError(f"formal {label} must stay below the official RAE-stream root") from exc
    if ".." in relative.parts:
        raise ValueError(f"formal {label} contains traversal components")
    current = root
    for component in relative.parts:
        current = current / component
        if current.is_symlink():
            raise ValueError(f"formal {label} contains a symlink component: {current}")
    resolved = candidate.resolve()
    if resolved != candidate:
        raise ValueError(f"formal {label} is not canonical: {candidate}")
    return candidate


def validate_dataset(
    *,
    data_root: str | Path,
    split_root: str | Path,
    manifest_path: str | Path,
    official_root: str | Path | None = None,
    expected_commit: str | None = None,
    expected_revision: str | None = None,
    allow_nonproduction: bool = False,
    require_production: bool = False,
    image_decode_samples: int = 8,
    prepare_receipt_path: str | Path | None = None,
    prepare_receipt_sha256: str | None = None,
    authority_path: str | Path | None = None,
    authority_sha256: str | None = None,
) -> dict[str, Any]:
    """Run all non-mutating checks and return a JSON-ready validation receipt."""

    raw_official_root = Path(official_root).resolve() if official_root is not None else None
    if require_production and raw_official_root is not None:
        data_root = _canonical_owned_path(data_root, raw_official_root, label="data root")
        split_root = _canonical_owned_path(split_root, raw_official_root, label="split root")
        manifest_path = _canonical_owned_path(manifest_path, raw_official_root, label="manifest")
        if prepare_receipt_path is not None:
            prepare_receipt_path = _canonical_owned_path(
                prepare_receipt_path, raw_official_root, label="prepare receipt"
            )
        # Code authority is deliberately external to the mutable checkout;
        # verify_code_authority performs its own canonical regular-file,
        # no-symlink, external-SHA admission.  Do not force it through the
        # checkout-owned data/receipt path gate above.
    else:
        data_root = Path(data_root).resolve()
        split_root = Path(split_root).resolve()
        manifest_path = Path(manifest_path).resolve()
    if require_production and prepare_receipt_sha256 is None:
        raise ValueError("formal validation requires an external prepare receipt SHA")
    if require_production and raw_official_root is None:
        raise ValueError("formal validation requires --official-root for code authority")
    if require_production and authority_path is None:
        raise ValueError("formal validation requires an external code authority")
    if require_production and authority_sha256 is None:
        raise ValueError("formal validation requires an external code authority SHA")
    if authority_path is not None and authority_sha256 is not None:
        expected_authority_sha = str(authority_sha256)
        if len(expected_authority_sha) != 64 or any(
            char not in "0123456789abcdef" for char in expected_authority_sha.lower()
        ):
            raise ValueError("code authority SHA must be a 64-character hexadecimal digest")
    elif authority_path is not None or authority_sha256 is not None:
        raise ValueError("authority_path and authority_sha256 must be supplied together")
    else:
        expected_authority_sha = None
    if prepare_receipt_sha256 is not None:
        expected_prepare_sha = str(prepare_receipt_sha256)
        if len(expected_prepare_sha) != 64 or any(
            char not in "0123456789abcdef" for char in expected_prepare_sha.lower()
        ):
            raise ValueError("prepare receipt SHA must be a 64-character hexadecimal digest")
    else:
        expected_prepare_sha = None
    if not data_root.is_dir():
        raise FileNotFoundError(data_root)
    if not split_root.is_dir():
        raise FileNotFoundError(split_root)
    if require_production:
        _assert_formal_layout_readonly(data_root, split_root, manifest_path)
    if require_production and official_root is None:
        raise ValueError("formal validation requires --official-root for converter byte binding")
    if require_production and prepare_receipt_path is None:
        raise ValueError("formal validation requires a prepare receipt")
    if require_production and expected_revision is None:
        expected_revision = STREAMVLN_REVISION
    if require_production and expected_revision != STREAMVLN_REVISION:
        raise ValueError("formal validation requires the fixed StreamVLN revision")
    if require_production and expected_commit not in (None, OFFICIAL_COMMIT):
        raise ValueError("formal validation requires the fixed official RAE commit")
    if require_production:
        expected_commit = OFFICIAL_COMMIT
    code_authority: dict[str, Any] | None = None
    if authority_path is not None and expected_authority_sha is not None:
        code_authority = verify_code_authority(
            raw_official_root if raw_official_root is not None else REPO_ROOT,
            authority_path,
            expected_sha256=expected_authority_sha,
        )
    if isinstance(image_decode_samples, bool) or int(image_decode_samples) < 0:
        raise ValueError("image_decode_samples must be a nonnegative integer")
    if require_production and int(image_decode_samples) != FORMAL_IMAGE_DECODE_SAMPLES:
        raise ValueError(
            f"formal validation fixes image_decode_samples={FORMAL_IMAGE_DECODE_SAMPLES}"
        )
    # Hash the exact manifest bytes before parsing and again after all checks.
    # This closes the in-place/atomic-replacement window where validated rows
    # could otherwise be paired with a different receipt hash.
    manifest_initial_sha256 = sha256_file(manifest_path)
    rows = read_jsonl(manifest_path)
    if not rows:
        raise ValueError("manifest is empty")
    prepare_receipt: dict[str, Any] | None = None
    if prepare_receipt_path is not None:
        receipt_path = Path(prepare_receipt_path).resolve()
        if not receipt_path.is_file():
            raise FileNotFoundError(receipt_path)
        actual_prepare_sha = sha256_file(receipt_path)
        if expected_prepare_sha is not None and actual_prepare_sha != expected_prepare_sha:
            raise ValueError("prepare receipt SHA does not match the externally pinned digest")
        try:
            loaded_receipt = json.loads(receipt_path.read_text(encoding="utf-8"))
        except Exception as exc:
            raise ValueError(f"could not parse prepare receipt {receipt_path}") from exc
        if not isinstance(loaded_receipt, dict):
            raise ValueError("prepare receipt must be a JSON object")
        prepare_receipt = loaded_receipt
        if require_production:
            if prepare_receipt.get("status") != "PASS" or prepare_receipt.get("production_eligible") is not True:
                raise ValueError("formal validation requires a PASS production prepare receipt")
            declared_receipt_sha = prepare_receipt.get("receipt_sha256")
            receipt_without_sha = dict(prepare_receipt)
            receipt_without_sha.pop("receipt_sha256", None)
            computed_receipt_sha = hashlib.sha256(
                json.dumps(receipt_without_sha, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")
            ).hexdigest()
            if declared_receipt_sha != computed_receipt_sha:
                raise ValueError("prepare receipt self-hash mismatch")
            if Path(str(prepare_receipt.get("manifest_path", ""))).resolve() != manifest_path:
                raise ValueError("prepare receipt belongs to a different manifest path")
            if prepare_receipt.get("manifest_sha256") != manifest_initial_sha256:
                raise ValueError("prepare receipt manifest SHA mismatch")
            if int(prepare_receipt.get("min_length", -1)) != FORMAL_MIN_LENGTH:
                raise ValueError("prepare receipt min_length is not the formal ABI value")
            if int(prepare_receipt.get("context_size", -1)) != FORMAL_CONTEXT_SIZE:
                raise ValueError("prepare receipt context_size mismatch")
            if int(prepare_receipt.get("len_traj_pred", -1)) != FORMAL_LEN_TRAJ_PRED:
                raise ValueError("prepare receipt len_traj_pred mismatch")
            if prepare_receipt.get("converter_version") != EXPECTED_CONVERTER_VERSION:
                raise ValueError("prepare receipt converter version mismatch")
            if prepare_receipt.get("immutable_data_tree") is not True:
                raise ValueError("formal validation requires an immutable data tree")
            if prepare_receipt.get("immutable_split_lists") is not True:
                raise ValueError("formal validation requires immutable traj-name split lists")
            if prepare_receipt.get("immutable_manifest") is not True:
                raise ValueError("formal validation requires an immutable manifest")
    expected_converter_sha: str | None = None
    expected_converter_source_sha256: dict[str, str] | None = None
    expected_converter_bundle_sha256: str | None = None
    if official_root is not None:
        official_path = Path(official_root).resolve()
        expected_converter_sha = verify_converter_source(official_path)
        expected_converter_source_sha256 = converter_closure_digest_map(official_path)
        expected_converter_bundle_sha256 = compute_converter_bundle_sha256(expected_converter_source_sha256)
    if require_production and prepare_receipt is not None:
        _verify_formal_prepare_receipt_identity(
            prepare_receipt,
            expected_converter_sha=str(expected_converter_sha),
            expected_converter_source_sha256=dict(expected_converter_source_sha256 or {}),
            expected_converter_bundle_sha256=str(expected_converter_bundle_sha256),
        )
        parent_flags = prepare_receipt.get("immutable_parent_dirs")
        expected_parent_flags = {
            str(data_root.parent): True,
        }
        if not isinstance(parent_flags, Mapping) or dict(parent_flags) != expected_parent_flags:
            raise ValueError("formal validation requires immutable generated parent directories")
    # A production manifest must be self-identifying even when a caller uses
    # the validator without an upstream checkout.  The stronger exact-byte
    # comparison below is enabled whenever ``official_root`` is supplied.
    enforce_converter_identity = bool(require_production or expected_converter_sha is not None)
    converter_versions: set[str] = set()
    converter_hashes: set[str] = set()
    seen_names: set[str] = set()
    status_counts: dict[str, int] = {}
    # Keep the ordered list as well as a set.  BaseDataset consumes the text
    # file as a list; silently accepting duplicate/reordered entries changes
    # sampling weights even when the set is unchanged.
    split_names: dict[str, list[str]] = {"train": [], "test": []}
    source_indices: dict[str, set[int]] = {"R2R": set(), "RxR": set()}
    dataset_row_counts: dict[str, int] = {"R2R": 0, "RxR": 0}
    frame_count = 0
    image_samples: list[Path] = []
    expected_source_roots: dict[str, Path] = {}
    source_hashes_checked: dict[str, tuple[str, tuple[str, ...]]] = {}
    immutable_identities: dict[str, dict[str, int]] | None = None
    if require_production and prepare_receipt is not None:
        source_entries = prepare_receipt.get("sources")
        if not isinstance(source_entries, list):
            raise ValueError("prepare receipt lacks effective source entries")
        for entry in source_entries:
            if not isinstance(entry, Mapping):
                raise ValueError("invalid prepare receipt source entry")
            dataset_key = str(entry.get("dataset", ""))
            effective = entry.get("effective_source_root")
            if not dataset_key or not isinstance(effective, str) or not effective:
                raise ValueError("prepare receipt source entry lacks effective_source_root")
            if dataset_key in expected_source_roots:
                raise ValueError("duplicate prepare receipt source dataset")
            if entry.get("source_mode") != "tar-selected":
                raise ValueError("formal validation requires tar-selected private source snapshots")
            if raw_official_root is not None:
                effective_path = _canonical_owned_path(
                    effective, raw_official_root, label=f"{dataset_key} effective source root"
                )
            else:
                effective_path = Path(effective).resolve()
            if not effective_path.is_dir():
                raise ValueError(f"prepare receipt effective source root is not a regular directory: {effective_path}")
            _assert_readonly_path(effective_path, label=f"{dataset_key} effective source root")
            expected_source_roots[dataset_key] = effective_path
        _verify_formal_source_parent_identity(
            prepare_receipt,
            list(expected_source_roots.values()),
        )
        immutable_identities = _verify_immutable_path_identities(
            prepare_receipt,
            raw_official_root if raw_official_root is not None else REPO_ROOT,
        )
        expected_identity_paths = {
            str(path.resolve())
            for path in {
                data_root,
                data_root.parent,
                data_root.parent.parent,
                split_root,
                split_root.parent,
                manifest_path,
                *(split_root / split for split in ("train", "test")),
                *(split_root / split / "traj_names.txt" for split in ("train", "test")),
                *expected_source_roots.values(),
                *(path.parent for path in expected_source_roots.values()),
            }
        }
        if set(immutable_identities) != expected_identity_paths:
            raise ValueError("prepare receipt immutable path identity set mismatch")
    for row_number, row in enumerate(rows, start=1):
        if enforce_converter_identity:
            converter_version = str(row.get("converter_version", ""))
            converter_sha = str(row.get("converter_sha256", ""))
            if converter_version != EXPECTED_CONVERTER_VERSION:
                raise ValueError(
                    f"manifest row {row_number} converter_version mismatch: {converter_version!r}"
                )
            if len(converter_sha) != 64 or any(ch not in "0123456789abcdef" for ch in converter_sha.lower()):
                raise ValueError(f"manifest row {row_number} has invalid converter SHA")
            if expected_converter_sha is not None and converter_sha != expected_converter_sha:
                raise ValueError(
                    f"manifest row {row_number} converter SHA does not match official converter bytes"
                )
            if expected_converter_source_sha256 is not None:
                source_identity = row.get("converter_source_sha256")
                if not isinstance(source_identity, Mapping):
                    raise ValueError(f"manifest row {row_number} is missing converter source closure SHA map")
                normalized_identity = {str(key): str(value) for key, value in source_identity.items()}
                if normalized_identity != expected_converter_source_sha256:
                    raise ValueError(
                        f"manifest row {row_number} converter source closure does not match reviewed bytes"
                    )
                bundle_identity = str(row.get("converter_bundle_sha256", ""))
                if bundle_identity != expected_converter_bundle_sha256:
                    raise ValueError(
                        f"manifest row {row_number} converter bundle SHA does not match reviewed closure"
                    )
            converter_versions.add(converter_version)
            converter_hashes.add(converter_sha)
        status = str(row.get("status", ""))
        status_counts[status] = status_counts.get(status, 0) + 1
        if row.get("measured_pose") is not False or row.get("pose_source") != "command-derived-se2":
            raise ValueError(f"manifest row {row_number} is not explicitly command-derived")
        name = str(row.get("trajectory_name", ""))
        if not name or Path(name).name != name or name in seen_names or ".." in Path(name).parts:
            raise ValueError(f"manifest row {row_number} has unsafe/duplicate trajectory name: {name!r}")
        seen_names.add(name)
        split = str(row.get("split", ""))
        if split not in split_names:
            raise ValueError(f"manifest row {row_number} has unknown split {split!r}")
        production = row.get("production_eligible")
        if require_production and production is not True:
            raise ValueError(
                "formal manifest requires production_eligible=true on every row"
            )
        if production is False and not allow_nonproduction:
            raise ValueError("manifest is marked non-production; pass --allow-nonproduction only for mini probes")
        if row.get("dataset") != "R2R" and row.get("dataset") != "RxR":
            raise ValueError(f"manifest row {row_number} has unsupported source dataset")
        dataset_name = str(row["dataset"])
        dataset_row_counts[dataset_name] += 1
        source_index = row.get("source_index")
        if not isinstance(source_index, int) or isinstance(source_index, bool) or source_index < 0:
            raise ValueError(f"manifest row {row_number} has invalid source_index")
        if source_index in source_indices[dataset_name]:
            raise ValueError(f"manifest row {row_number} duplicates source_index")
        source_indices[dataset_name].add(source_index)
        if require_production and row.get("source_id") != f"{dataset_name}:{source_index}":
            raise ValueError(f"formal manifest row {row_number} source_id mismatch")
        if expected_revision is not None and row.get("source_revision") != expected_revision:
            raise ValueError(f"manifest row {row_number} source revision mismatch")
        annotation_hash = str(row.get("annotation_row_sha256", ""))
        if len(annotation_hash) != 64 or any(ch not in "0123456789abcdef" for ch in annotation_hash.lower()):
            raise ValueError(f"manifest row {row_number} has invalid annotation row SHA")
        try:
            expected_scene = scene_token_from_video(str(row.get("video", "")))
        except Exception as exc:
            raise ValueError(f"manifest row {row_number} has invalid video scene token") from exc
        if row.get("scene_token") != expected_scene:
            raise ValueError(f"manifest row {row_number} scene token mismatch")
        if split != split_for_scene(expected_scene):
            raise ValueError(f"manifest row {row_number} split does not match deterministic scene split")
        basename = Path(str(row.get("video", ""))).name
        expected_name = f"{dataset_name.lower()}__{basename}"
        if name != expected_name:
            raise ValueError(f"manifest row {row_number} trajectory name mismatch")
        actions_value = row.get("command_actions")
        if not isinstance(actions_value, list) or any(
            isinstance(action, bool) or not isinstance(action, int) for action in actions_value
        ):
            raise ValueError(f"manifest row {row_number} is missing command_actions")
        actions = [int(action) for action in actions_value]
        action_digest = row.get("command_actions_sha256")
        if require_production and not isinstance(action_digest, str):
            raise ValueError(f"formal manifest row {row_number} lacks command_actions_sha256")
        if action_digest is not None and action_digest != _action_digest(actions):
            raise ValueError(f"manifest row {row_number} command action SHA mismatch")
        try:
            integrate_actions(actions)
        except Exception as exc:
            raise ValueError(f"manifest row {row_number} command-derived action sequence is invalid") from exc
        if status == "excluded_short":
            if row.get("output_dir") is not None:
                raise ValueError(f"short row {row_number} unexpectedly has output_dir")
            expected_short_count = row.get("frame_count")
            if not isinstance(expected_short_count, int) or isinstance(expected_short_count, bool) or expected_short_count != len(actions):
                raise ValueError(f"short row {row_number} action/frame count mismatch")
            if len(actions) >= FORMAL_MIN_LENGTH:
                raise ValueError(f"formal short row {row_number} has enough frames to materialize")
            continue
        if status != "materialized":
            raise ValueError(f"manifest row {row_number} has unsupported status {status!r}")
        if require_production and len(actions) < FORMAL_MIN_LENGTH:
            raise ValueError(
                f"formal materialized row {row_number} is shorter than {FORMAL_MIN_LENGTH} frames"
            )
        output_value = row.get("output_dir")
        if not isinstance(output_value, str) or not output_value:
            raise ValueError(f"manifest row {row_number} missing output_dir")
        output_raw = Path(output_value)
        if not output_raw.is_absolute():
            raise ValueError(f"manifest row {row_number} output path must be absolute and canonical")
        expected_output = data_root / name
        output = output_raw
        if output.parent != data_root or output.name != name or output.resolve() != expected_output:
            raise ValueError(
                f"manifest row {row_number} output path is not the canonical direct child {expected_output}"
            )
        if output.is_symlink() or not output.is_dir() or output.resolve() != output:
            raise FileNotFoundError(output)
        if require_production:
            _assert_readonly_path(output, label=f"manifest row {row_number} trajectory directory")
        if require_production:
            expected_root = expected_source_roots.get(dataset_name)
            if expected_root is None:
                raise ValueError(f"prepare receipt has no effective source root for {dataset_name}")
            row_source_root = row.get("source_root")
            if not isinstance(row_source_root, str) or Path(row_source_root).resolve() != expected_root:
                raise ValueError(f"manifest row {row_number} source_root does not match prepare receipt")
        frames = _numeric_frames(output)
        expected_count = int(row.get("frame_count", -1))
        if len(frames) != expected_count:
            raise ValueError(f"manifest row {row_number} frame_count mismatch")
        if len(actions) != len(frames):
            raise ValueError(f"manifest row {row_number} action/frame alignment mismatch")
        _validate_pickle(
            output / "traj_data.pkl",
            len(frames),
            actions,
            expected_sha256=(str(row.get("traj_data_sha256")) if row.get("traj_data_sha256") is not None else None),
        )
        if require_production:
            _assert_readonly_path(output / "traj_data.pkl", label=f"manifest row {row_number} pickle")
        if require_production and row.get("traj_data_sha256") is None:
            raise ValueError(f"formal manifest row {row_number} lacks traj_data_sha256")
        frame_digest = row.get("frame_sequence_sha256")
        if require_production and not isinstance(frame_digest, str):
            raise ValueError(f"formal manifest row {row_number} lacks frame_sequence_sha256")
        if frame_digest is not None:
            actual_frame_digest = frame_sequence_sha256(frames)
            if actual_frame_digest != frame_digest:
                raise ValueError(f"manifest row {row_number} frame sequence SHA mismatch")
        if require_production:
            # Bind each output frame to the exact selected-source pathname
            # that the converter recorded.  Hardlinks preserve inode identity;
            # cross-filesystem symlinks are accepted only when they resolve to
            # that same path below the receipt-bound staging root.
            source_root = expected_source_roots[dataset_name]
            source_dir = find_frame_dir(source_root, str(row["video"]))
            _assert_readonly_path(source_dir, label=f"manifest row {row_number} source frame directory")
            declared_subdir = row.get("source_frame_subdir")
            try:
                actual_subdir = str(source_dir.relative_to(source_root))
            except ValueError as exc:
                raise ValueError(f"manifest row {row_number} source frame directory escapes root") from exc
            if declared_subdir != actual_subdir:
                raise ValueError(f"manifest row {row_number} source frame subdir mismatch")
            source_frames = numeric_frame_paths(source_dir)
            if len(source_frames) != len(frames):
                raise ValueError(f"manifest row {row_number} source/output frame count mismatch")
            for frame, source_frame in zip(frames, source_frames):
                if source_frame.is_symlink() or not source_frame.is_file() or source_frame.resolve() != source_frame:
                    raise ValueError(f"manifest row {row_number} source frame is not a canonical regular file")
                _assert_readonly_path(source_frame, label=f"manifest row {row_number} source frame")
                source_resolved = source_frame.resolve()
                if frame.is_symlink():
                    if frame.resolve() != source_resolved:
                        raise ValueError(f"manifest row {row_number} frame symlink source mismatch")
                else:
                    try:
                        if not os.path.samefile(frame, source_resolved):
                            raise ValueError(f"manifest row {row_number} frame inode source mismatch")
                    except FileNotFoundError as exc:
                        raise ValueError(f"manifest row {row_number} source frame is missing") from exc
            source_frame_digest = row.get("source_frame_sequence_sha256")
            if not isinstance(source_frame_digest, str):
                raise ValueError(f"formal manifest row {row_number} lacks source frame sequence SHA")
            if not isinstance(frame_digest, str):
                raise ValueError(f"formal manifest row {row_number} lacks output frame sequence SHA")
            try:
                _verify_source_frame_digest(
                    frames,
                    source_frames,
                    declared_output_digest=frame_digest,
                    declared_source_digest=source_frame_digest,
                )
            except ValueError as exc:
                raise ValueError(f"manifest row {row_number} source frame digest mismatch: {exc}") from exc
        for frame in frames:
            if require_production:
                if frame.is_symlink():
                    _assert_readonly_path(
                        frame.resolve(), label=f"manifest row {row_number} output frame target"
                    )
                else:
                    _assert_readonly_path(frame, label=f"manifest row {row_number} output frame")
            if frame.is_symlink():
                target = frame.resolve()
                source_root = row.get("source_root")
                if not isinstance(source_root, str):
                    raise ValueError(f"manifest row {row_number} symlink lacks source_root")
                try:
                    target.relative_to(Path(source_root).resolve())
                except ValueError as exc:
                    raise ValueError(f"manifest row {row_number} symlink escapes source root") from exc
        split_names[split].append(name)
        frame_count += len(frames)
        if len(image_samples) < int(image_decode_samples):
            # Manifest order is canonical, so this is deterministic and does
            # not require a second full directory walk.  Structural checks
            # still cover every frame name/count; decoding is intentionally a
            # bounded payload-integrity gate.
            image_samples.append(frames[0])

    for split in ("train", "test"):
        names_path = split_root / split / "traj_names.txt"
        if not names_path.is_file():
            raise FileNotFoundError(names_path)
        raw_lines = names_path.read_text(encoding="utf-8").splitlines()
        if any(not line.strip() for line in raw_lines):
            raise ValueError(f"{split} traj_names.txt contains blank lines")
        listed = [line.strip() for line in raw_lines]
        if len(listed) != len(set(listed)):
            raise ValueError(f"{split} traj_names.txt contains duplicate trajectory names")
        expected = sorted(split_names[split])
        if listed != expected:
            raise ValueError(f"{split} traj_names.txt does not exactly match canonical manifest order")
    if set(split_names["train"]) & set(split_names["test"]):
        raise ValueError("train/test trajectory leakage")
    if not split_names["train"] or not split_names["test"]:
        raise ValueError("both train and test splits must be non-empty for a formal manifest")

    if require_production and prepare_receipt is not None:
        declared_split_hashes = prepare_receipt.get("split_list_sha256")
        if not isinstance(declared_split_hashes, Mapping):
            raise ValueError("prepare receipt lacks split list SHA map")
        actual_split_hashes = {
            split: sha256_file(split_root / split / "traj_names.txt")
            for split in ("train", "test")
        }
        if dict(declared_split_hashes) != actual_split_hashes:
            raise ValueError("prepare receipt split list SHA mismatch")
        for split in ("train", "test"):
            _assert_readonly_path(
                split_root / split / "traj_names.txt",
                label=f"formal {split} traj_names.txt",
            )

    if require_production:
        if set(dataset_row_counts) != {"R2R", "RxR"}:
            raise ValueError("formal manifest requires both R2R and RxR rows")
        for dataset_name, expected_count in STREAMVLN_ANNOTATION_ROW_COUNTS.items():
            if dataset_row_counts[dataset_name] != expected_count:
                raise ValueError(
                    f"formal manifest {dataset_name} row count {dataset_row_counts[dataset_name]} "
                    f"does not cover the fixed annotation ({expected_count})"
                )
            if source_indices[dataset_name] != set(range(expected_count)):
                raise ValueError(f"formal manifest {dataset_name} source_index coverage is incomplete")
        if prepare_receipt is None:
            raise ValueError("formal validation requires a prepare receipt")
        receipt_counts = prepare_receipt.get("counts")
        if not isinstance(receipt_counts, Mapping):
            raise ValueError("prepare receipt lacks counts")
        expected_counts = {
            "records_seen": len(rows),
            "materialized": status_counts.get("materialized", 0),
            "excluded_short": status_counts.get("excluded_short", 0),
        }
        for key, value in expected_counts.items():
            if int(receipt_counts.get(key, -1)) != int(value):
                raise ValueError(f"prepare receipt {key} count mismatch")
        split_counts = prepare_receipt.get("split_counts")
        if not isinstance(split_counts, Mapping):
            raise ValueError("prepare receipt lacks split_counts")
        if int(split_counts.get("train", -1)) != len(split_names["train"]) or int(
            split_counts.get("test", -1)
        ) != len(split_names["test"]):
            raise ValueError("prepare receipt split count mismatch")
        if int(prepare_receipt.get("frame_count_output", -1)) != frame_count:
            raise ValueError("prepare receipt frame count mismatch")
        receipt_sources = prepare_receipt.get("source_metadata_initial")
        if not isinstance(receipt_sources, list) or {str(item.get("dataset")) for item in receipt_sources if isinstance(item, Mapping)} != {"R2R", "RxR"}:
            raise ValueError("prepare receipt source metadata is incomplete")
        receipt_sources_final = prepare_receipt.get("source_metadata_final")
        if receipt_sources_final != receipt_sources:
            raise ValueError("prepare receipt source identity changed before publication")
        # Re-hash the released annotation and parent archives once at the
        # formal boundary.  This binds the receipt to current bytes rather
        # than trusting self-reported 64-hex provenance fields.
        for source in receipt_sources:
            if not isinstance(source, Mapping):
                raise ValueError("invalid source metadata entry")
            dataset_name = str(source.get("dataset"))
            annotation_path = Path(str(source.get("annotation_path", ""))).resolve()
            if not annotation_path.is_file() or sha256_file(annotation_path) != STREAMVLN_ANNOTATION_SHA256[dataset_name]:
                raise ValueError(f"{dataset_name} annotation bytes do not match fixed release")
            archive_paths_value = source.get("archive_parts")
            if archive_paths_value is None:
                archive_path_value = source.get("archive_path")
                archive_paths_value = [archive_path_value] if archive_path_value else []
            archive_paths = [Path(str(value)).resolve() for value in archive_paths_value]
            expected_archives = STREAMVLN_ARCHIVE_SHA256[dataset_name]
            if len(archive_paths) != len(expected_archives):
                raise ValueError(f"{dataset_name} archive part count mismatch")
            actual_archives = tuple(sha256_file(path) for path in archive_paths if path.is_file())
            if actual_archives != expected_archives:
                raise ValueError(f"{dataset_name} parent archive bytes do not match fixed release")
            source_hashes_checked[dataset_name] = (
                sha256_file(annotation_path),
                actual_archives,
            )
            if source.get("annotation_sha256") != STREAMVLN_ANNOTATION_SHA256[dataset_name]:
                raise ValueError(f"{dataset_name} receipt annotation identity mismatch")
            # Bind every manifest row to the actual released annotation row,
            # not merely to a self-reported 64-hex hash.  This proves the
            # video/action/BOS sequence that generated the SE(2) pose.
            annotation_records = load_annotation_file(annotation_path, dataset_name)
            manifest_rows = [row for row in rows if row.get("dataset") == dataset_name]
            if len(annotation_records) != STREAMVLN_ANNOTATION_ROW_COUNTS[dataset_name]:
                raise ValueError(f"{dataset_name} annotation row count changed at validation")
            by_index = {int(row["source_index"]): row for row in manifest_rows}
            if set(by_index) != set(range(len(annotation_records))):
                raise ValueError(f"{dataset_name} manifest does not cover annotation source indices")
            for index, record in enumerate(annotation_records):
                row = by_index[index]
                if (
                    row.get("video") != record.video
                    or row.get("annotation_row_sha256") != record.row_sha256
                    or row.get("command_actions") != [int(action) for action in record.actions]
                    or row.get("scene_token") != record.scene_token
                ):
                    raise ValueError(f"{dataset_name} manifest row {index} does not match released annotation")

    for sample in image_samples:
        _decode_jpeg_sample(sample)

    if official_root is not None:
        # Re-read the closure after walking the manifest.  A long validation
        # must not publish PASS if a converter dependency changes mid-check.
        final_root = Path(official_root).resolve()
        final_entry = verify_converter_source(final_root)
        final_map = converter_closure_digest_map(final_root)
        if final_entry != expected_converter_sha or final_map != expected_converter_source_sha256:
            raise RuntimeError("converter source closure changed during validation")
        if code_authority is not None and authority_path is not None and expected_authority_sha is not None:
            final_authority = verify_code_authority(
                final_root,
                authority_path,
                expected_sha256=expected_authority_sha,
            )
            if final_authority != code_authority:
                raise RuntimeError("code authority surface changed during validation")
    if require_production:
        # Re-hash every released input after parsing/binding all annotation
        # rows.  This closes the annotation-hash→JSON-load race without a
        # second tar extraction and prevents a transient replacement from
        # being published as a PASS receipt.
        for dataset_name, (initial_annotation_sha, initial_archive_shas) in source_hashes_checked.items():
            source_entry = next(
                entry for entry in prepare_receipt["sources"] if str(entry.get("dataset")) == dataset_name
            )
            annotation_path = Path(str(source_entry["annotation_path"])).resolve()
            archive_value = source_entry.get("archive_parts")
            if archive_value is None:
                archive_value = [source_entry.get("archive_path")]
            archive_paths = [Path(str(value)).resolve() for value in archive_value]
            final_annotation_sha = sha256_file(annotation_path)
            final_archive_shas = tuple(sha256_file(path) for path in archive_paths)
            if final_annotation_sha != initial_annotation_sha or final_archive_shas != initial_archive_shas:
                raise RuntimeError(f"{dataset_name} released input changed during validation")
    manifest_final_sha256 = sha256_file(manifest_path)
    if manifest_final_sha256 != manifest_initial_sha256:
        raise RuntimeError("manifest changed during validation")
    if require_production and prepare_receipt_path is not None:
        final_prepare_sha = sha256_file(Path(prepare_receipt_path).resolve())
        if expected_prepare_sha is None or final_prepare_sha != expected_prepare_sha:
            raise RuntimeError("prepare receipt changed during validation")
        final_layout = _verify_immutable_path_identities(
            prepare_receipt,
            raw_official_root if raw_official_root is not None else REPO_ROOT,
        )
        if immutable_identities is None or final_layout != immutable_identities:
            raise RuntimeError("immutable data/source path identity changed during validation")

    upstream = None
    if official_root is not None:
        upstream = verify_upstream_source(Path(official_root), expected_commit=expected_commit or OFFICIAL_COMMIT)
    receipt: dict[str, Any] = {
        "status": "PASS",
        "production_eligible": bool(require_production),
        "claim_boundary": (
            "FORMAL_DATA_VALIDATION_ONLY"
            if require_production
            else "TRAINING_MECHANICS_ONLY_NOT_NAVIGATION_PERFORMANCE"
        ),
        "manifest_path": str(manifest_path),
        "manifest_sha256": manifest_initial_sha256,
        "data_root": str(data_root),
        "split_root": str(split_root),
        "rows": len(rows),
        "status_counts": status_counts,
        "train_trajectories": len(split_names["train"]),
        "test_trajectories": len(split_names["test"]),
        "frame_count_materialized": frame_count,
        "image_decode_samples": len(image_samples),
        "official_source": upstream,
        "prepare_receipt_path": str(Path(prepare_receipt_path).resolve()) if prepare_receipt_path else None,
        "prepare_receipt_sha256": (
            sha256_file(Path(prepare_receipt_path).resolve()) if prepare_receipt_path else None
        ),
        "code_authority": code_authority,
    }
    if converter_hashes:
        receipt["converter_version"] = sorted(converter_versions)[0]
        receipt["converter_sha256"] = sorted(converter_hashes)[0]
        receipt["converter_identity_checked"] = expected_converter_sha is not None
        if expected_converter_source_sha256 is not None:
            receipt["converter_source_sha256"] = dict(expected_converter_source_sha256)
            receipt["converter_bundle_sha256"] = expected_converter_bundle_sha256
    return receipt


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-root", type=Path, required=True)
    parser.add_argument("--split-root", type=Path, required=True)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--official-root", type=Path)
    parser.add_argument("--expected-commit")
    parser.add_argument("--expected-revision")
    parser.add_argument("--receipt", type=Path)
    parser.add_argument("--prepare-receipt", type=Path)
    parser.add_argument("--prepare-receipt-sha256")
    parser.add_argument("--authority", type=Path)
    parser.add_argument("--authority-sha256")
    parser.add_argument("--allow-nonproduction", action="store_true")
    parser.add_argument(
        "--require-production",
        action="store_true",
        help="require explicit production_eligible=true (the formal training gate)",
    )
    parser.add_argument(
        "--image-decode-samples",
        type=int,
        default=8,
        help="deterministic bounded number of first-frame JPEG samples to decode",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_arg_parser().parse_args(argv)
    try:
        receipt = validate_dataset(
            data_root=args.data_root,
            split_root=args.split_root,
            manifest_path=args.manifest,
            official_root=args.official_root,
            expected_commit=args.expected_commit,
            expected_revision=args.expected_revision,
            allow_nonproduction=args.allow_nonproduction,
            require_production=args.require_production,
            image_decode_samples=args.image_decode_samples,
            prepare_receipt_path=args.prepare_receipt,
            prepare_receipt_sha256=args.prepare_receipt_sha256,
            authority_path=args.authority,
            authority_sha256=args.authority_sha256,
        )
        if args.receipt is not None:
            _atomic_json(args.receipt.resolve(), receipt)
    except Exception as exc:
        print(f"validate_rae_stream: ERROR: {exc}", file=sys.stderr)
        return 2
    print(json.dumps(receipt, ensure_ascii=False, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
